#!/bin/bash
#SBATCH -p gpu20
#SBATCH -t 10:00:00
#SBATCH --gres gpu:1
#SBATCH -o /BS/fscil/work/code/CEC-CVPR2021/logs/slurm-%A_%a.out

# Note that you can submit to gpu22 or gpu20
# python train.py -project base -dataset cifar100 -start_session 0 -gpu 1 -new_mode ft_dot -epochs_new 1 -epochs_base 1 -save_path_prefix "exp_corrected_joint_session"
# python train.py -project base -dataset cub200 -start_session 1 -gpu 0 -new_mode ft_dot -epochs_new 100 -save_path_prefix exp_corrected_joint_session -model_dir ./checkpoint/base_training_ckpt/cub200/base/ft_dot_label_smoothing/session0_80_091.pth -label_smoothing 0.5
# python train.py -project base -dataset cub200 -start_session 1 -gpu 0 -new_mode ft_cos -epochs_new 100 -save_path_prefix exp_corrected_joint_session -model_dir ./checkpoint/base_training_ckpt/cub200/base/ft_dot_label_smoothing/session0_80_091.pth -label_smoothing 0.5
# python train.py -project base -dataset mini_imagenet -start_session 1 -gpu 0 -new_mode ft_cos -epochs_new 150 -save_path_prefix exp_corrected_joint_session -model_dir ./checkpoint/base_training_ckpt/mini_imagenet/base/ft_dot/session0_70_500.pth -label_smoothing 0.5
# python train.py -project base -dataset cifar100 -start_session 0 -gpu 0 -new_mode ft_cos -epochs_new 150 -save_path_prefix "exp_corrected_joint_session" -model_dir ./checkpoint/base_training_ckpt/cifar100/base/ft_dot/session0_72_90.pth
# python train.py -project base -dataset cub200 -start_session 0 -gpu 0 -base_mode ft_cos -new_mode ft_cos -epochs_new 100 -save_path_prefix exp_corrected_joint_session -label_smoothing 0.5
# python train.py -project base -dataset mini_imagenet -gpu 0 -epochs_new 150 -save_path_prefix exp_skip_color_jitter_ -label_smoothing 0.5 -skip_color_jitter
# cmd="python train.py -project base -dataset cub200 -start_session 1 -gpu 0 -new_mode ft_dot -epochs_new 150 -save_path_prefix exp_corrected_joint_session -model_dir ./checkpoint/base_training_ckpt/cub200/base/ft_dot/session0_70_976.pth -label_smoothing 0.5"
# cmd="python train.py -project base -dataset mini_imagenet -start_session 1 -gpu 0 -new_mode ft_dot -epochs_new 150  -save_path_prefix exp_corrected_joint_phase -model_dir ./checkpoint/base_training_ckpt/mini_imagenet/base/ft_dot/session0_70_500.pth -validation_metric acc"
# cmd="python train.py -project base_weight_reg -dataset mini_imagenet -start_session 1 -gpu 0 -new_mode ft_dot -epochs_new 150  -save_path_prefix exp_corrected_joint_phase -model_dir ./checkpoint/base_training_ckpt/mini_imagenet/base/ft_dot/session0_70_500.pth"
# cmd="python train.py -project cec -dataset cub200 -epochs_base 100 -episode_way 15 -episode_shot 1 -episode_query 10 -low_way 15 -low_shot 1 -lr_base 0.0002 -lrg 0.0002 -step 20 -gamma 0.5 -gpu 0 -model_dir params/cub200/session0_max_acc7552_cos.pth"
# cmd="python train.py -project base -dataset mini_imagenet -start_session 0 -gpu 0 -base_mode ft_dot -new_mode ft_dot -epochs_new 150 -save_path_prefix exp_minet_fixed_base_mode"
# cmd="python train.py -project base -dataset mini_imagenet -start_session 0 -gpu 0 -base_mode ft_dot -new_mode ft_dot -epochs_new 150 -save_path_prefix exp_minet_fixed_base_mode -label_smoothing 0.5"
# cmd="python train.py -project base_temp -dataset mini_imagenet -start_session 1 -gpu 0 -base_mode ft_dot -new_mode ft_dot -epochs_new 150 -save_path_prefix exp_minet_fixed_base_mode -model_dir ./checkpoint/base_training_ckpt/mini_imagenet/base/ft_dot/session0_71_05.pth -t_scaling"
# cmd="python train.py -project base_temp -dataset mini_imagenet -start_session 1 -gpu 0 -base_mode ft_dot -new_mode ft_dot -epochs_new 150 -save_path_prefix exp_minet_fixed_base_mode -model_dir ./checkpoint/base_training_ckpt/mini_imagenet/base/ft_dot/session0_71_05.pth -t_scaling -save_path_prefix exp_minet_update_novel_3.4"
# cmd="python train.py -project base_classification_mean -dataset mini_imagenet -start_session 1 -gpu 0 -base_mode ft_l2 -new_mode ft_l2 -epochs_new 150 -save_path_prefix exp_mode_change -model_dir checkpoint/mini_imagenet/base_classification_mean/exp_mode_change_ft_l2-ft_l2-data_init-start_0/Epo_100-Lr_0.1000-Step_40-Gam_0.10-Bs_128-Mom_0.90-ftLR_0.100-ftEpoch_150-opt_sgd-vm_hm-ls_0.00/session0_max_acc.pth"
# cmd="python train.py -project base_mixup -dataset mini_imagenet -start_session 0 -new_mode ft_dot -gpu 0 -epochs_new 150"
# cmd="python train.py -project base_data_aug -dataset mini_imagenet -start_session 0 -new_mode ft_dot -gpu 0 -epochs_new 150 -data_aug"
# cmd="python train.py -project base_mixup -dataset cub200 -start_session 0 -new_mode ft_dot -gpu 0 -epochs_new 100 -epochs_base 500"
# cmd="python train.py -project base_mixup -dataset cub200 -start_session 0 -gpu 0 -new_mode ft_dot -epochs_new 100 -label_smoothing 0.5"
# cmd="python train.py -project base_mixup -dataset cifar100 -start_session 0 -gpu 0 -new_mode ft_dot -epochs_new 150 -epochs_base 200"
# cmd="python train.py -project base_projection -dataset mini_imagenet -start_session 0 -gpu 0 -new_mode ft_dot -epochs_new 100"
# cmd="python train.py -project base_balanced_testing -dataset cub200 -start_session 0 -gpu 0 -base_mode ft_dot -new_mode ft_dot -epochs_new 150 -save_path_prefix exp_cub_balanced_testing"
# cmd="python train.py -project base_balanced_testing -dataset cifar100 -start_session 0 -gpu 0 -base_mode ft_dot -new_mode ft_dot -epochs_new 150 -save_path_prefix exp_cifar_balanced_testing"
# cmd="python train.py -project base_mixup -dataset cub200 -start_session 0 -gpu 0 -new_mode ft_dot -epochs_new 150 -epochs_base 500 -label_smoothing 0.5"
# cmd="python train.py -project base -dataset cub200 -start_session 1 -gpu 0 -new_mode ft_dot -epochs_new 100 -save_path_prefix exp_corrected_joint_session -model_dir ./checkpoint/base_training_ckpt/cub200/base/ft_dot_label_smoothing/session0_80_091.pth -label_smoothing 0.5"
# cmd="python train.py -project base_balanced_testing -dataset cub200 -start_session 0 -gpu 0 -base_mode ft_dot -new_mode ft_dot -epochs_new 150 -save_path_prefix exp_cub_balanced_testing -label_smoothing 0.5"
# cmd="python train.py -project base -dataset cub200 -start_session 1 -gpu 0 -new_mode ft_dot -epochs_new 100 -save_path_prefix exp_corrected_carry_forward -model_dir ./checkpoint/base_training_ckpt/cub200/base/ft_dot_label_smoothing/session0_80_091.pth -label_smoothing 0.5"
# cmd="python train.py -project base -dataset cub200 -start_session 0 -gpu 0,1 -new_mode ft_dot -save_path_prefix exp_baseline2.0+adam -label_smoothing 0.5 -validation_metric_novel none -epochs_novel 60 -optimizer adam -lr_base 3e-4 -lr_new 3e-4"
# cmd="python train.py -start_session 1 -joint_mixup -novel_mixup -project base_mixup -dataset cub200 -epochs_base 200 -gpu 0 -new_mode ft_dot -epochs_novel 60 -save_path_prefix mixup_novel_joint -label_smoothing 0.95 -mixup_alpha 0.3 -model_dir checkpoint/cub200/base_mixup/exp_ls+mixup_search_ft_dot-ft_dot-data_init-start_0/Epo_200-Lr_0.1000-Step_40-Gam_0.10-Bs_128-Mom_0.90-ftLR_0.100-ftnEpoch_60-jEpoch_100-opt_sgd-vm_hm-ls_0.95-ma_0.30/session0_max_acc.pth"
# cmd="python train.py -start_session 1 -novel_mixup -project base_mixup -dataset cub200 -epochs_base 200 -gpu 0 -new_mode ft_dot -epochs_novel 60 -save_path_prefix baseline4.0 -label_smoothing 0.95 -mixup_alpha 0.3 -model_dir checkpoint/cub200/base_mixup/exp_ls+mixup_search_ft_dot-ft_dot-data_init-start_0/Epo_200-Lr_0.1000-Step_40-Gam_0.10-Bs_128-Mom_0.90-ftLR_0.100-ftnEpoch_60-jEpoch_100-opt_sgd-vm_hm-ls_0.95-ma_0.30/session0_max_acc.pth"
# cmd="python train.py -start_session 0 -novel_mixup -project base_mixup -dataset cub200 -epochs_base 200 -gpu 0,1 -new_mode ft_dot -epochs_novel 60 -save_path_prefix baseline_4.0+color_jitter -label_smoothing 0.95 -mixup_alpha 0.3 -color_jitter"
# cmd="python train.py -start_session 1 -novel_mixup -project base_mixup_interfc -dataset cub200 -epochs_base 200 -gpu 0 -new_mode ft_dot -epochs_novel 60 -save_path_prefix baseline4.0+interfc -label_smoothing 0.95 -mixup_alpha 0.3 -model_dir checkpoint/cub200/base_mixup/exp_ls+mixup_search_ft_dot-ft_dot-data_init-start_0/Epo_200-Lr_0.1000-Step_40-Gam_0.10-Bs_128-Mom_0.90-ftLR_0.100-ftnEpoch_60-jEpoch_100-opt_sgd-vm_hm-ls_0.95-ma_0.30/session0_max_acc.pth"
# cmd="python train.py -project base_mixup_cec_linear -dataset cub200 -start_session 0 -novel_mixup -new_mode ft_dot -epochs_novel 60 -save_path_prefix cec+pretraining+novel_ft+linear -label_smoothing 0.95 -mixup_alpha 0.3 -epochs_base 100 -episode_way 15 -episode_shot 1 -episode_query 10 -low_way 15 -low_shot 1 -lr_base 0.0002 -lrg 0.0002 -step 20 -gamma 0.5 -gpu 0 -model_dir checkpoint/cub200/base_mixup/exp_ls+mixup_search_ft_dot-ft_dot-data_init-start_0/Epo_200-Lr_0.1000-Step_40-Gam_0.10-Bs_128-Mom_0.90-ftLR_0.100-ftnEpoch_60-jEpoch_100-opt_sgd-vm_hm-ls_0.95-ma_0.30/session0_max_acc.pth"
# cmd="python train.py -start_session 1 -joint_mixup -project base_mixup -dataset cub200 -epochs_base 200 -gpu 0 -new_mode ft_dot -epochs_novel 60 -save_path_prefix mixup_novel_joint -label_smoothing 0.95 -mixup_alpha 0.3 -model_dir checkpoint/cub200/base_mixup/exp_ls+mixup_search_ft_dot-ft_dot-data_init-start_0/Epo_200-Lr_0.1000-Step_40-Gam_0.10-Bs_128-Mom_0.90-ftLR_0.100-ftnEpoch_60-jEpoch_100-opt_sgd-vm_hm-ls_0.95-ma_0.30/session0_max_acc.pth"
# cmd="python train.py -project base_mixup -dataset cub200 -start_session 0 -epochs_base 200 -gpu 0 -new_mode ft_dot -save_path_prefix manifold_mixup -epochs_novel 60 -label_smoothing 0.95 -mixup_alpha 0.3 -validation_metric_novel none -mixup_hidden"
# cmd="python train.py -project base_mixup -dataset cub200 -start_session 0 -epochs_base 200 -gpu 0 -new_mode ft_dot -save_path_prefix baseline3.0_rerun -epochs_novel 60 -label_smoothing 0.95 -mixup_alpha 0.3 -validation_metric_novel none -mixup_base -mixup_novel"
# cmd="python train.py -project base_mixup -dataset cub200 -start_session 0 -epochs_base 200 -gpu 0 -new_mode ft_dot -save_path_prefix manifold_mixup+novel_mixup -epochs_novel 60 -label_smoothing 0.95 -mixup_alpha 0.3 -validation_metric_novel none -mixup_hidden -mixup_novel"
# cmd="python train.py -project base_mixup_att -mixup_novel -dataset cub200 -start_session 0 -new_mode ft_dot -epochs_novel 60 -save_path_prefix vanilla_self_attention -label_smoothing 0.95 -mixup_alpha 0.3 -epochs_base 200 -gpu 0 -model_dir checkpoint/cub200/base_mixup/exp_ls+mixup_search_ft_dot-ft_dot-data_init-start_0/Epo_200-Lr_0.1000-Step_40-Gam_0.10-Bs_128-Mom_0.90-ftLR_0.100-ftnEpoch_60-jEpoch_100-opt_sgd-vm_hm-ls_0.95-ma_0.30/session0_max_acc.pth"
# cmd="python train.py -project base_mixup -dataset mini_imagenet -start_session 0 -epochs_base 200 -gpu 0 -new_mode ft_dot -save_path_prefix baseline4.0 -label_smoothing 0.95 -mixup_alpha 0.3 -validation_metric_novel none -mixup_base -mixup_novel"
# cmd="python train.py -project base_mixup -dataset mini_imagenet -start_session 0 -epochs_base 200 -gpu 0 -new_mode ft_dot -save_path_prefix baseline4.0-label_smoothing -mixup_alpha 0.3 -validation_metric_novel none -mixup_base -mixup_novel"
# cmd="python train.py -project base_mixup -dataset cifar100 -start_session 0 -epochs_base 200 -gpu 0 -new_mode ft_dot -save_path_prefix baseline4.0 -label_smoothing 0.95 -mixup_alpha 0.3 -validation_metric_novel none -mixup_base -mixup_novel"
# cmd="python train.py -project base_s2m2 -dataset cub200 -start_session 0 -epochs_base 200 -gpu 0 -new_mode ft_dot -save_path_prefix baseline4.0+rot_pretrain -label_smoothing 0.95 -mixup_alpha 0.3 -validation_metric_novel none -mixup_base -mixup_novel"
# cmd="python train.py -project base_s2m2 -dataset cub200 -start_session 0 -epochs_base 200 -gpu 1 -new_mode ft_dot -save_path_prefix baseline4.0+rot_aux -label_smoothing 0.95 -mixup_alpha 0.3 -validation_metric_novel none"
# cmd="python train.py -project base_mixup_unit -dataset cub200 -start_session 1 -epochs_base 200 -gpu 0 -new_mode ft_dot -save_path_prefix projection_head_novel -validation_metric_novel none -label_smoothing 0.5 -model_dir checkpoint/cub200/base_mixup_unit/projection_head_ft_dot-ft_dot-data_init-start_0/Epo_200-Lr_0.1000-Step_40-Gam_0.10-Bs_128-Mom_0.90-ftLR_0.100-ftnEpoch_60-jEpoch_100-opt_sgd-vm_hm-ls_0.50-ma_0.30/session0_max_acc.pth"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0,1 -save_path_prefix baseline6.0-mixup-joint_label_smoothing_test+high_batch_count -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 512 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0,1 -save_path_prefix baseline6.0-mixup-joint_label_smoothing_test+1024 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0,1 -save_path_prefix baseline6.0-mixup-joint_label_smoothing_test+high_batch_count -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 512 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel -sup_con_temp 0.1"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0,1 -save_path_prefix baseline6.0-mixup-joint_label_smoothing_test+high_batch_count -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 512 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 128 -new_mode ft_dot -train_base_in_novel"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix baseline6.0-mixup-joint_label_smoothing_test+1024 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix baseline6.0-mixup-joint_label_smoothing_test+1536 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1536 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel"
# cmd="python sweep.py -sweep_json sweep_config/sup_con_sweep.json -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix supcon_sweep -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -end_session 1"
# cmd="python sweep.py -sweep_json sweep_config/sup_con_1024_temp.json -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix sweep+1024 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel"
# cmd="python sweep.py -sweep_json sweep_config/sup_con_1024_feat.json -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix sweep+1024+feat -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -epochs_sup_con 100 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 4096 -sup_con_temp 0.2 -rand_aug_sup_con"
# cmd="python train.py -project base_supcon_multi -dataset cub200 -start_session 1 -gpu 0,1,2 -save_path_prefix multi_gpu_test_2048 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 2048 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0,1,2 -save_path_prefix sup_con -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -epochs_sup_con 100 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 6144 -sup_con_temp 0.05"
# cmd="python sweep.py -sweep_json sweep_config/sup_con_sweep_base_session.json -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0,1,2 -save_path_prefix sweep -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -end_session 1"
# cmd="python train.py -project base_supcon_multi -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix skip_sup_con_head -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -skip_sup_con_head"
# cmd="python train.py -project base_supcon_multi -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix testing_normalisation -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -sup_con_feat_dim 512 -skip_encode_norm"
# cmd="python train.py -project base_supcon_multi -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix skip_sup_con_head -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -skip_sup_con_head -sup_con_feat_dim 512"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 256 -epochs_sup_con 100 -lr_decay_epochs_sup_con '50,80'"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 128 -epochs_sup_con 100 -lr_decay_epochs_sup_con '50,80' -cosine"
### === Mini imagement sup con experiments ===
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+1 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 128 -epochs_sup_con 110"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+2 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 128 -sup_con_feat_dim 128 -epochs_sup_con 110"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+3 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 32 -sup_con_feat_dim 128 -epochs_sup_con 110"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+4 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 128 -epochs_sup_con 110 -warm_sup_con"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+5 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 128 -epochs_sup_con 110 -cosine_sup_con "
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+6 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 256 -epochs_sup_con 110"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+7 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 512 -epochs_sup_con 110"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+8 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 256 -sup_con_feat_dim 128 -epochs_sup_con 110"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+9 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 128 -epochs_sup_con 110 -rand_aug_sup_con"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+10 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 1024 -epochs_sup_con 110"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+11 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 64 -epochs_sup_con 110"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+2 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 128 -sup_con_feat_dim 128 -epochs_sup_con 110 -rand_aug_sup_con"

#### === Mini imagenet higher decay ===
# python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_decay1 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 128 -epochs_sup_con 110 -rand_aug_sup_con -decay_sup_con 0.0005
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_decay2 -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 128 -epochs_sup_con 100 -rand_aug_sup_con -lr_sup_con 0.1 -lr_decay_epochs_sup_con 50"
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix cross_entropy_test -validation_metric_novel none -ce_pretrain -batch_size_base 256 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel"

#### === CUB200 without non linearity in new head ===
# cmd="python train.py -project base_supcon_multi -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix baseline6.0-mixup-joint_label_smoothing_test+1024-nonlinearity -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel -model_dir "
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+fixed_normalisation -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+fixed_normalisation -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 350 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+pro -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 512 -new_mode ft_dot -train_base_in_novel -use_sup_con_head"

# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+margin0.4 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -margin_sup_con 0.4"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+margin0.6 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -margin_sup_con 0.6"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+margin0.8 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -margin_sup_con 0.8"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 512 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -mixup_sup_con"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+temp0.1 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 512 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -sup_con_temp 0.1"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+temp0.2 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 512 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -sup_con_temp 0.2"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+temp0.3 -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 512 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -sup_con_temp 0.3"

# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+fixed_normalisation -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_mixup -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -mixup_sup_con"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_mixup_view_based -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 50 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm -mixup_sup_con"
# cmd="python train.py -project base_mixup_contrastive_sr -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix best_cub200_77+fixed_normalisation+high_epochs -validation_metric_novel none -sup_con_pretrain -batch_size_sup_con 1024 -batch_size_joint 16 -epochs_sup_con 350 -cosine_sup_con -classifier_last_layer linear -warm_sup_con -train_inter -proto_init_sup_con -sup_con_freeze_backbone -sup_con_feat_dim 256 -new_mode ft_dot -train_base_in_novel -use_sup_con_head -skip_encode_norm"

#### === Sup con Minet wiht sup con head ===
# cmd="python train.py -project base_supcon_multi -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix sup_con_best+1+usesupconhead -validation_metric_novel none -sup_con_pretrain -batch_size_joint 16 -classifier_last_layer linear -train_inter -proto_init_sup_con -sup_con_freeze_backbone -new_mode ft_dot -train_base_in_novel -batch_size_sup_con 64 -sup_con_feat_dim 128 -epochs_sup_con 110 -use_sup_con_head"

# cmd="python train.py -project base_supcon_sr -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix test_joint_output=1024 -sup_con_pretrain -batch_size_joint 16 -train_inter -model_dir /BS/fscil/work/code/solo-learn/trained_models/supcon/ab0y2n6u/supcon_minet_1024_acc_85_65.ckpt -reserve_mode all -epochs_base 10 -criterion cosine -joint_supcon -reserve_vector_count 1024 -proj_output_dim 1024"

#### === Thesis runs ====
# Cosine Runs
# cmd="python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_cosine_result1 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -simplex_lam 1"
# cmd="python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_cosine_result2 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -simplex_lam 1"

# Ablations
# cmd="python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_ablation1 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -novel_bias -simplex_lam 0 -sup_lam 0"
# cmd=" python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_ablation2 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -novel_bias -simplex_lam 0"
# cmd=" python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_ablation3 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -novel_bias -simplex_lam 1 -sup_lam 0"


# Other pull losses
# cmd="python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_ablation_pull1 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -novel_bias -simplex_lam 1 -pull_criterion_base xent -pull_criterion_novel xent"
# cmd="python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_ablation_pull2 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -novel_bias -simplex_lam 1 -pull_criterion_base xent+cosine -pull_criterion_novel xent+cosine "
# cmd="python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_ablation_pull3 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -novel_bias -simplex_lam 1 -pull_criterion_base cosine-squared -pull_criterion_novel cosine-squared"


# Assignment schemes
# cmd=" python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -save_path_prefix thesis_ablation4 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/r4obzzs3/supcon-minet-auto-augment-r4obzzs3-ep=353.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -novel_bias -simplex_lam 1 -assignment_mode random"


# Base session without pretrain
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -lr_base 0.025 -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -batch_size_base 256"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain_proj -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -lr_base 0.025 -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -batch_size_base 256"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain_mixup -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -lr_base 0.025 -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -batch_size_base 256 -mix_lam 0.1"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -lr_base 0.025 -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -batch_size_base 256 -base_schedule Cosine"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain_equalcosblam -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.5 -novel_bias -proj_type proj_ncfscil -lr_base 0.025 -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -batch_size_base 256 -base_schedule Cosine"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain_hgiher_reg -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -lr_base 0.025 -decay 5e-3 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -batch_size_base 256"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain_lower_lr -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -batch_size_base 256 -lr_base 0.025 -lr_base_encoder 0.025"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain_bs512 -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -lr_base 0.025 -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -batch_size_base 512 -base_schedule Cosine"
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -save_path_prefix no_pretrain -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.25 -simplex_lam 1"
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+higherbaseepochs -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir -reserve_mode all -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.25 -simplex_lam 1 -base_schedule Cosine"
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+higherbaseepochs -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -reserve_mode all -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.25 -simplex_lam 1 -base_schedule Cosine"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain_bs512 -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -lr_base 0.025 -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -base_schedule Cosine -batch_size_sup_con 512"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj+mix0.1 -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine -mix_lam 0.1"
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+higherbaseepochs+higherbs+totallr0.25 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -reserve_mode all -epochs_base 300 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.25 -lr_base_encoder 0.25 -simplex_lam 1 -base_schedule Cosine -batch_size_sup_con 512"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix pretrain+lower_lr+cosesched -model_dir /BS/fscil/work/code/solo-learn/trained_models/supcon/ep0hcst3/pretrain_cub_augmix_78_81.ckpt -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine"
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+higherbaseepochs+higherbs+totallr0.1 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -reserve_mode all -epochs_base 300 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.1 -lr_base_encoder 0.1 -simplex_lam 1 -base_schedule Cosine -batch_size_sup_con 512"

#### === Optimizer Ablations ====
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj+inc_adam -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine -optimizer sgd -optimizer_joint adam -lr_new 3e-4"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj+inc_adamw -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine -optimizer sgd -optimizer_joint adamw -lr_new 3e-4"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj+base_adam -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 3e-4 -lr_base_encoder 3e-4 -base_schedule Cosine -optimizer adam -optimizer_joint sgd"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj+base_adamw -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 3e-4 -lr_base_encoder 3e-4 -base_schedule Cosine -optimizer adamw -optimizer_joint sgd"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj+base_adam+inc_adam -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 3e-4 -lr_base_encoder 3e-4 -lr_new 3e-4 -base_schedule Cosine -optimizer adam -optimizer_joint adam"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj+base_adamw+inc_adamw -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 3e-4 -lr_base_encoder 3e-4 -lr_new 3e-4 -base_schedule Cosine -optimizer adamw -optimizer_joint adamw"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -base_schedule Cosine -decay 0.05 -lr_base 0.0001 -optimizer adamw -lr_base_encoder 0.0001 -save_path_prefix best_adamw"


# Best CUB200
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix no_pretrain+lower_lr+cosesched+proj -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine"

# CUB200 pretrain knn_score
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix knn_score_pretrain+prep -model_dir /BS/fscil/work/code/solo-learn/trained_models/supcon/ep0hcst3/pretrain_cub_augmix_78_81.ckpt -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj_ncfscil -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine -end_session 1"
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix knn_score_prep -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj         -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine -end_session 1"

# Spread aware CUB200
# cmd="python train.py -project base_supcon_srv3 -dataset cub200 -start_session 1 -gpu 0 -save_path_prefix spread_aware -sup_con_pretrain -batch_size_joint 32 -train_inter -epochs_joint 100 -reserve_mode full -epochs_base 100 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-5 -cos_b_lam 0.6 -novel_bias -proj_type proj -decay 5e-4 -epochs_simplex 5000 -lr_new 0.05 -simplex_lam 1 -fine_tune_backbone_base -lr_base 0.025 -lr_base_encoder 0.025 -base_schedule Cosine -spread_aware"

# Spread aware cifar100
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -save_path_prefix cifar+spread_aware -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/s7rclcq9/pretrain_cub_aa_epoch480_81_183.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.25 -simplex_lam 1 -spread_aware"

# Simplex in lam
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -save_path_prefix cifar_best+simplexinc_onlynew -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir  /BS/fscil/work/code/solo-learn/trained_models/supcon/s7rclcq9/pretrain_cub_aa_epoch480_81_183.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel cosine -pull_criterion_base cosine -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.25 -simplex_lam 1 -simplex_lam_inc 1"

# Simplex 2048
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir /BS/fscil/work/code/solo-learn/trained_models/supcon/fw7y0yf8/supsim+pod2048_ep280_acc_80_033.ckpt -reserve_mode full -epochs_base 10 -pull_criterion_novel xent -pull_criterion_base xent -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.25 -simplex_lam 1 -perturb_epsilon_base 9e-05 -perturb_epsilon_inc 9e-05 -save_path_prefix pod2048+full_cifar_pert_search+perturb_epsilon_base-9e05-perturb_epsilon_inc-9e05 -proj_output_dim 2048 -epochs_simplex 5000"

# Simplex 1024
# cmd="python train.py -project base_supcon_srv3 -dataset cifar100 -start_session 1 -gpu 0 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir /BS/fscil/work/code/solo-learn/trained_models/supcon/g85m2wt0/supsimclr_280_pod1024_79_533.ckpt -reserve_mode full -epochs_base 10 -pull_criterion_novel xent -pull_criterion_base xent -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 5e-4 -cos_b_lam 0 -novel_bias -lr_base 0.25 -simplex_lam 1 -perturb_epsilon_base 9e-05 -perturb_epsilon_inc 9e-05 -save_path_prefix pod1024_full_cifar_pert_search+perturb_epsilon_base-9e05-perturb_epsilon_inc-9e05 -proj_output_dim 1024 -epochs_simplex 5000"

cmd="python train.py -project base_supcon_srv3 -dataset mini_imagenet -start_session 1 -gpu 0 -sup_con_pretrain -batch_size_joint 64 -train_inter -epochs_joint 100 -model_dir /BS/fscil/work/code/solo-learn/trained_models/supcon/muqbelec/minet_e380_01simclr_acc85_95.ckpt -reserve_mode all -epochs_base 10 -pull_criterion_novel xent -pull_criterion_base xent -joint_supcon -validation_metric hm -joint_schedule Cosine -decay_new 1e-4 -decay 1e-4 -cos_b_lam 0 -simplex_lam 1 -save_path_prefix minet_simclr+carry+exemplars1 -novel_bias -exemplars_count 1"

# print start time and command to log
# Use tail -1 to read the logs
echo $(date)
echo "using GPU ${CUDA_VISIBLE_DEVICES}"
echo $cmd


# start command
$cmd